import pandas as pd

series = pd.Series([1,2,3,4,5], index = ['first','sec','third','four','fifth'] , name = 'name')
print(series)
onco = pd.read_csv("C:/Users/riddh/Downloads/oncologists_nyc.csv",index_col = 0)
# print(onco)
# print(onco.shape)
# print(onco.head())
# print(onco.name)
# print(onco.columns)
# print(onco['phone'])
# print(onco.iloc[:,0])
# print(onco.iloc[1]['name'])
# print(onco.iloc[0])
# print(onco.iloc[:,0])
# print(onco.iloc[:3,0])
# print(onco.loc['ChIJlZ4P8qb3wokRwmH1-7F0TEM','name'])
# onco = onco.reset_index()
# print(onco.loc[0,'name']) 
# print(onco.loc[:3,['street','phone','state']])#iloc uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So 0:10 will select entries 0,...,9. loc, meanwhile, indexes inclusively. So 0:10 will select entries 0,...,10.
# print(onco.set_index('name'))
Data = pd.DataFrame({'Name':['Riddhi Nashine','shruti','rohan','amruta','jashnavi'],'College':['GHRaisoni','ghraisoni','ghraisoni','ycc','ycc'],'color':['blue','yellow','green','red',None]})
print(Data.loc[Data.color.isnull()])
print(Data)
# print(Data.Name == "shruti")
# print(Data.loc[Data.College == 'ghraisoni'])
# print(Data.loc[(Data.College == 'ghraisoni') | (Data.Name  == 'rohan') ])
# print(Data.loc[(Data.College == 'ghraisoni') & (Data.Name  == 'rohan') ])
# print(Data.loc[Data.color.isin(['red','blue'])])
Data['House'] = 'Same'
Data['index_backward'] = range(len(Data),0,-1)
print(Data)