import pandas as pd
Data = pd.DataFrame({'Name':['Riddhi Nashine','shruti'],'College':['GHRaisoni','ghraisoni']},index = [1,2])
print(Data)
series = pd.Series([1,2,3,4,5], index = ['first','sec','third','four','fifth'] , name = 'name')
print(series)
onco = pd.read_csv("C:/Users/riddh/Downloads/oncologists_nyc.csv",index_col = 0)
# print(onco)
print(onco.shape)
print(onco.head())
print(onco.name)
print(onco.columns)
print(onco['phone'])
print(onco.iloc[:,0])
print(onco.iloc[1]['name'])
